
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello
  owner: cj

resources:
  - deployment.yaml
  - service.yaml
  - hps.yaml
  - namespace.yaml